export function generateCicdJenkins(model) {
  const p = model.pipeline
  const fw = p.automationFramework
  const lang = p.language
  const reports = p.reports
  const artifacts = p.artifacts
  const trigger = p.trigger

  const installStage = fw === 'playwright'
    ? `    stage('Install Dependencies') {
      steps {
        sh 'npm ci'
      }
    }
    stage('Install Browsers') {
      steps {
        sh 'npx playwright install --with-deps'
      }
    }`
    : fw === 'selenium'
    ? seleniumJenkinsStage(lang)
    : appiumJenkinsStage(lang, p.platform)

  const execMode = (p.executionOptions?.executionMode || p.executionMode || 'Headless').toLowerCase()
  const hasRetry = (p.executionOptions?.retries || 0) > 0 || p.enableRetry
  const workersFlag = (p.executionOptions?.workers || 0) > 1 ? ` --workers=${p.executionOptions.workers}` : ''
  const retriesFlag = (p.executionOptions?.retries || 0) > 0 ? ` --retries=${p.executionOptions.retries}` : ''
  const slowMoFlag = (p.executionOptions?.slowMo || 0) > 0 ? ` --slow-mo=${p.executionOptions.slowMo}` : ''
  const suiteGrep = buildSuiteGrep(p.testSuites)
  const loadJenkinsEnv = buildJenkinsEnvLoad(p.projectVariables, p.activeEnvironment)
  const testStage = fw === 'playwright'
    ? `    stage('Run Tests') {
      steps {
        ${loadJenkinsEnv}sh 'npx playwright test${execMode === 'headed' ? ' --headed' : ''}${reports.html ? '' : ' --reporter=list'}${suiteGrep}${workersFlag}${retriesFlag}${slowMoFlag}'
      }
      post {
        always {
          junst 'test-results/**/*.xml'
        }
      }
    }`
    : fw === 'selenium'
    ? seleniumTestJenkinsStage(lang)
    : appiumTestJenkinsStage(lang)

  const reportStage = generateJenkinsReportStage(reports)
  const archiveStage = generateJenkinsArchiveStage(artifacts)
  const timeoutMinutes = p.executionOptions?.timeout || 60

  const triggerConfig = trigger === 'Scheduled Run'
    ? `    triggers {
        cron('H 6 * * 1-5')
    }`
    : ''

  let content = `// ${p.pipelineName || `${fwLabel(fw)} CI/CD Pipeline`}
// Generated by PlayGen CI/CD Generator
// Automation Framework: ${fwLabel(fw)} | Language: ${lang}
// https://playgen.app

pipeline {
    agent any

    options {
        timeout(time: ${timeoutMinutes}, unit: 'MINUTES')
    }

    tools {
        ${fw === 'playwright' || lang === 'JavaScript' ? "nodejs 'NodeJS'" : lang === 'Java' ? "maven 'Maven'" : lang === 'Python' ? '' : "dotnet 'DotNet'"}
    }

  environment {
    CI = 'true'${p.activeEnvironment ? `\n    APP_ENV = '${p.activeEnvironment}'` : ''}
  }

${triggerConfig}
    stages {
${installStage}
${testStage}
${reportStage}    }
${archiveStage}
}
`

  return [
    { name: 'Jenkinsfile', content: content.trimStart() },
  ]
}

function buildSuiteGrep(suites) {
  const enabled = (suites || []).filter((s) => s.enabled && s.tags && s.tags.length > 0)
  if (enabled.length === 0) return ''
  const tags = [...new Set(enabled.flatMap((s) => s.tags))]
  return ` --grep "${tags.join('|')}"`
}

function buildJenkinsEnvLoad(vars, activeEnv) {
  const hasVars = (vars || []).some((v) => v.key)
  const hasEnv = !!activeEnv
  if (!hasVars && !hasEnv) return ''
  const cmds = []
  if (hasVars) cmds.push('cat .env.variables >> .env')
  if (hasEnv) cmds.push(`cat .env.${activeEnv} >> .env`)
  return cmds.map((c) => `sh '${c} || true'\n        `).join('')
}

function fwLabel(fw) {
  return { playwright: 'Playwright', selenium: 'Selenium', appium: 'Appium' }[fw] || fw
}

function seleniumJenkinsStage(lang) {
  switch (lang) {
    case 'Java':
      return `    stage('Install Dependencies') {
      steps {
        sh 'mvn clean install -DskipTests'
      }
    }`
    case 'Python':
      return `    stage('Install Dependencies') {
      steps {
        sh 'pip install -r requirements.txt'
      }
    }`
    case 'JavaScript':
      return `    stage('Install Dependencies') {
      steps {
        sh 'npm ci'
      }
    }`
    case 'C#':
      return `    stage('Restore Packages') {
      steps {
        sh 'dotnet restore'
      }
    }`
    default:
      return `    stage('Install Dependencies') {
      steps {
        sh 'npm ci'
      }
    }`
  }
}

function seleniumTestJenkinsStage(lang) {
  const cmd = lang === 'Java' ? 'mvn test' : lang === 'Python' ? 'pytest -v' : lang === 'JavaScript' ? 'npx mocha --timeout 30000' : 'dotnet test'
  return `    stage('Run Tests') {
      steps {
        sh '${cmd}'
      }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }`
}

function appiumJenkinsStage(lang, platform) {
  const driver = platform === 'iOS' ? 'xcuitest' : 'uiautomator2'
  const langStage = lang === 'Java'
    ? `    stage('Install Dependencies') {
      steps {
        sh 'mvn clean install -DskipTests'
      }
    }`
    : lang === 'Python'
    ? `    stage('Install Dependencies') {
      steps {
        sh 'pip install -r requirements.txt'
      }
    }`
    : lang === 'JavaScript'
    ? `    stage('Install Dependencies') {
      steps {
        sh 'npm ci'
      }
    }`
    : `    stage('Restore Packages') {
      steps {
        sh 'dotnet restore'
      }
    }`

  return `${langStage}
    stage('Setup Appium') {
      steps {
        sh 'npm install -g appium'
        sh 'appium driver install ${driver}'
        sh 'appium &'
        sh 'sleep 5'
      }
    }`
}

function appiumTestJenkinsStage(lang) {
  const cmd = lang === 'Java' ? 'mvn test' : lang === 'Python' ? 'pytest -v' : lang === 'JavaScript' ? 'npx wdio' : 'dotnet test'
  return `    stage('Run Tests') {
      steps {
        sh '${cmd}'
      }
    }`
}

function generateJenkinsReportStage(reports) {
  const steps = []
  if (reports.html) {
    steps.push(`    stage('Generate HTML Report') {
      steps {
        sh 'mkdir -p reports'
        sh 'echo "Report generated at \\$(date)" > reports/index.html'
      }
    }`)
  }
  if (reports.allure) {
    steps.push(`    stage('Generate Allure Report') {
      steps {
        sh 'allure generate allure-results --clean -o allure-report'
      }
    }`)
  }
  return steps.length > 0 ? steps.join('\n\n') + '\n\n' : ''
}

function generateJenkinsArchiveStage(artifacts) {
  const patterns = []
  if (artifacts.reports) patterns.push('reports/**')
  if (artifacts.screenshots) patterns.push('**/screenshots/**')
  if (artifacts.videos) patterns.push('**/videos/**')
  if (artifacts.logs) patterns.push('**/logs/**')

  if (patterns.length === 0) return ''

  return `
    post {
        always {
            archiveArtifacts artifacts: '${patterns.join(', ')}', fingerprint: true
        }
    }`
}

export function generateCicdJenkinsExplanation(model) {
  const p = model.pipeline
  return `## Pipeline Explanation: Jenkins

This Jenkins Pipeline (Declarative Pipeline) is configured to run ${p.automationFramework} tests on your Jenkins server.

### Pipeline Structure

- **Agent**: Uses 'any' agent, allowing Jenkins to run on any available executor. For ${p.automationFramework} testing, consider using a node with browser capabilities.

- **Tools**: ${langTool(p.language)} is configured as a tool in the Jenkins global configuration.

- **Stages**:
  1. **Install Dependencies** - ${fwDepDesc(p)}
  2. **${fwStageLabel(p)}** - ${fwStageDesc(p)}
  3. **Run Tests** - Executes the test suite${p.executionMode === 'headless' ? ' in headless mode' : ''}${p.enableRetry ? ' with automatic retry on failure' : ''}
  4. **Generate Reports** - ${reportDesc(p.reports)}
  5. **Archive Artifacts** - ${artifactDesc(p.artifacts)}

### Key Features

- **Trigger**: ${triggerDesc(p.trigger)}
- **Pipeline Type**: Declarative Pipeline (Jenkinsfile)
- **Post Actions**: Always archives test artifacts, even on failure

### Prerequisites

- Jenkins with Pipeline plugin installed
- ${langTool(p.language)} installed and configured in Jenkins global tools
- ${p.automationFramework === 'playwright' ? 'NodeJS plugin for Jenkins' : 'Appropriate build tool plugin'}`
}

function langTool(lang) {
  if (lang === 'JavaScript' || lang === 'TypeScript') return 'NodeJS'
  if (lang === 'Java') return 'Maven'
  if (lang === 'Python') return 'Python'
  if (lang === 'C#') return '.NET'
  return 'NodeJS'
}

function fwDepDesc(p) {
  if (p.automationFramework === 'playwright') return 'Installs npm dependencies and Playwright browsers'
  if (p.automationFramework === 'selenium') return `Installs ${p.language} dependencies via ${p.language === 'Java' ? 'Maven' : p.language === 'Python' ? 'pip' : p.language === 'JavaScript' ? 'npm' : 'NuGet'}`
  return 'Installs Appium globally and platform-specific drivers'
}

function fwStageLabel(p) {
  if (p.automationFramework === 'playwright') return 'Install Browsers'
  if (p.automationFramework === 'appium') return 'Setup Appium'
  return 'Setup Drivers'
}

function fwStageDesc(p) {
  if (p.automationFramework === 'playwright') return 'Installs Chromium, Firefox, and WebKit browsers with system dependencies'
  if (p.automationFramework === 'appium') return `Installs Appium server and ${p.platform} driver`
  return 'Configures browser drivers for Selenium WebDriver'
}

function reportDesc(reports) {
  const r = []
  if (reports.html) r.push('HTML report')
  if (reports.allure) r.push('Allure report')
  return r.length > 0 ? `Generates ${r.join(', ')}` : 'No reports configured'
}

function artifactDesc(artifacts) {
  const a = []
  if (artifacts.reports) a.push('test reports')
  if (artifacts.screenshots) a.push('screenshots')
  if (artifacts.videos) a.push('videos')
  if (artifacts.logs) a.push('logs')
  return a.length > 0 ? `Archives ${a.join(', ')}` : 'No artifacts configured'
}

function triggerDesc(trigger) {
  if (trigger === 'Scheduled Run') return 'Scheduled cron job (weekdays at 6 AM)'
  if (trigger === 'Push') return 'Triggered on code push'
  if (trigger === 'Pull Request') return 'Triggered on pull request'
  return 'Manual trigger via Jenkins UI'
}

export function generateCicdJenkinsChecklist(model) {
  const p = model.pipeline
  const items = []

  const checks = [
    { label: 'Jenkins platform selected', passed: true },
    { label: `${fwLabel(p.automationFramework)} framework selected`, passed: true },
    { label: `${p.language} language configured`, passed: true },
    { label: 'Dependencies installed correctly', passed: true },
    { label: `Pipeline triggers configured (${p.trigger})`, passed: true },
    { label: `${p.browser} browser configured`, passed: true },
    { label: `Headless mode recommended for CI`, passed: p.executionMode === 'Headless' },
    { label: 'HTML report configuration', passed: p.reports.html },
    { label: 'Allure report configuration', passed: p.reports.allure },
    { label: 'Artifacts configured for archive', passed: p.artifacts.reports || p.artifacts.screenshots || p.artifacts.videos || p.artifacts.logs },
    { label: 'JUnit test results publishing', passed: p.reports.junit },
  ]

  items.push({ category: 'Pipeline Validation', items: checks })

  const warnings = []
  if (!p.reports.html && !p.reports.allure) {
    warnings.push({ label: 'Missing report configuration - no reports will be generated', passed: false })
  }
  if (!p.artifacts.reports && !p.artifacts.screenshots && !p.artifacts.videos && !p.artifacts.logs) {
    warnings.push({ label: 'Missing artifact archive - test results will not be stored', passed: false })
  }
  if (p.executionMode === 'Headed') {
    warnings.push({ label: 'Headed mode not recommended for CI environments', passed: false })
  }
  if (warnings.length > 0) {
    items.push({ category: 'Warnings', items: warnings })
  }

  return items
}

export function generateCicdJenkinsBestPractices() {
  return [
    {
      title: 'Use Declarative Pipeline Syntax',
      description: 'Declarative Pipelines provide a simpler, more structured syntax with better error handling and built-in post-action support.',
    },
    {
      title: 'Configure Jenkins Global Tools',
      description: 'Define NodeJS, Maven, JDK, and .NET SDK versions in Jenkins global tool configuration, then reference them via the tools directive.',
    },
    {
      title: 'Use Post Actions for Cleanup',
      description: 'Always archive artifacts in the post section with `always` condition to preserve test results even after build failures.',
    },
    {
      title: 'Run Headless in CI',
      description: 'Configure browsers to run in headless mode in Jenkins to avoid X11 display dependencies on the build server.',
    },
    {
      title: 'Use Pipeline Libraries',
      description: 'Extract common pipeline logic into shared libraries for reuse across multiple projects and teams.',
    },
    {
      title: 'Set Build Timeouts',
      description: 'Configure pipeline timeouts to prevent builds from running indefinitely and consuming Jenkins executor slots.',
    },
    {
      title: 'Leverage Parallel Stages',
      description: 'Run tests in parallel across multiple browsers or devices using the parallel directive to reduce pipeline duration.',
    },
  ]
}
