export function generateCicdGitlabCi(model) {
  const p = model.pipeline
  const fw = p.automationFramework
  const lang = p.language
  const os = p.operatingSystem.toLowerCase()
  const reports = p.reports
  const artifacts = p.artifacts
  const trigger = p.trigger

  const image = fw === 'playwright'
    ? 'mcr.microsoft.com/playwright:v1.51.0-focal'
    : os === 'macos' ? 'macos:latest' : 'ubuntu:latest'

  const beforeScript = fw === 'playwright'
    ? 'before_script:\n  - npm ci\n  - npx playwright install --with-deps\n'
    : fw === 'selenium'
    ? seleniumBeforeScript(lang)
    : appiumBeforeScript(lang, p.platform)

  const suiteGrep = buildSuiteGrep(p.testSuites)
  const execMode = (p.executionOptions?.executionMode || p.executionMode || 'Headless').toLowerCase()
  const workersFlag = (p.executionOptions?.workers || 0) > 1 ? ` --workers=${p.executionOptions.workers}` : ''
  const retriesFlag = (p.executionOptions?.retries || 0) > 0 ? ` --retries=${p.executionOptions.retries}` : ''
  const slowMoFlag = (p.executionOptions?.slowMo || 0) > 0 ? ` --slow-mo=${p.executionOptions.slowMo}` : ''
  const testScript = fw === 'playwright'
    ? `    - npx playwright test${execMode === 'headed' ? ' --headed' : ''}${reports.html ? '' : ' --reporter=list'}${suiteGrep}${workersFlag}${retriesFlag}${slowMoFlag}`
    : fw === 'selenium'
    ? seleniumTestScript(lang) + suiteGrep
    : appiumTestScript(lang) + suiteGrep

  const artifactPaths = []
  if (artifacts.reports) artifactPaths.push('reports/')
  if (artifacts.screenshots) artifactPaths.push('screenshots/')
  if (artifacts.videos) artifactPaths.push('videos/')
  if (artifacts.logs) artifactPaths.push('logs/')

  const artifactSection = artifactPaths.length > 0
    ? `\n  artifacts:\n    when: always\n    paths:\n      - ${artifactPaths.join('\n      - ')}\n    expire_in: 7 days`
    : ''

  const reportSection = generateGitlabReports(reports)

  const stages = fw === 'playwright'
    ? ['test']
    : ['install', 'test']

  const workflowName = p.pipelineName || `${fwLabel(fw)} CI/CD Pipeline`

  let content = `# ${workflowName}
# Generated by PlayGen CI/CD Generator
# Automation Framework: ${fwLabel(fw)} | Language: ${lang}
# https://playgen.app

stages:
${stages.map(s => `  - ${s}`).join('\n')}

variables:
  CI: "true"${p.activeEnvironment ? `\n  APP_ENV: "${p.activeEnvironment}"` : ''}

${buildGitlabCache(p.cacheConfig)}
${buildGitlabEnvLoad(p.projectVariables, p.activeEnvironment)}
${fw === 'playwright' ? '' : ''}${fwLabel(fw)}-Tests:
  stage: test
  image: ${image}
${beforeScript ? `  ${beforeScript}` : ''}  script:
${testScript}
${reportSection}${artifactSection}
`

  if (trigger === 'Scheduled Run') {
    content = `include:
  - template: Auto-DevOps.gitlab-ci.yml

` + content
  }

  return [
    { name: '.gitlab-ci.yml', content: content.trimStart() },
  ]
}

function buildSuiteGrep(suites) {
  const enabled = (suites || []).filter((s) => s.enabled && s.tags && s.tags.length > 0)
  if (enabled.length === 0) return ''
  const tags = [...new Set(enabled.flatMap((s) => s.tags))]
  return ` --grep "${tags.join('|')}"`
}

function buildGitlabCache(cacheConfig) {
  const pm = cacheConfig?.packageManager
  if (!pm) return ''
  const paths = {
    npm: '    - node_modules/',
    maven: '    - .m2/',
    gradle: '    - .gradle/',
    pip: '    - .cache/pip/',
    nuget: '    - .nuget/packages/',
  }
  const p = paths[pm]
  if (!p) return ''
  return `cache:
  key: ${'{CI_COMMIT_REF_SLUG}'}
  paths:
${p}
`
}

function buildGitlabEnvLoad(vars, activeEnv) {
  const hasVars = (vars || []).some((v) => v.key)
  const hasEnv = !!activeEnv
  if (!hasVars && !hasEnv) return ''
  const cmds = []
  if (hasVars) cmds.push('cat .env.variables >> .env')
  if (hasEnv) cmds.push(`cat .env.${activeEnv} >> .env`)
  return `  before_script:
${cmds.map((c) => `    - ${c}`).join('\n')}
  artifacts:
    reports:
      dotenv: .env
`
}

function fwLabel(fw) {
  return { playwright: 'Playwright', selenium: 'Selenium', appium: 'Appium' }[fw] || fw
}

function seleniumBeforeScript(lang) {
  switch (lang) {
    case 'Java':
      return `before_script:
  - apt-get update && apt-get install -y maven
  - mvn clean install -DskipTests
`
    case 'Python':
      return `before_script:
  - pip install -r requirements.txt
`
    case 'JavaScript':
      return `before_script:
  - npm ci
`
    case 'C#':
      return `before_script:
  - dotnet restore
`
    default:
      return `before_script:
  - npm ci
`
  }
}

function seleniumTestScript(lang) {
  switch (lang) {
    case 'Java': return '    - mvn test'
    case 'Python': return '    - pytest -v'
    case 'JavaScript': return '    - npx mocha --timeout 30000'
    case 'C#': return '    - dotnet test'
    default: return '    - mvn test'
  }
}

function appiumBeforeScript(lang, platform) {
  const driver = platform === 'iOS' ? 'xcuitest' : 'uiautomator2'
  const langScript = lang === 'Java'
    ? `  - apt-get update && apt-get install -y maven
  - mvn clean install -DskipTests`
    : lang === 'Python'
    ? `  - pip install -r requirements.txt`
    : lang === 'JavaScript'
    ? `  - npm ci`
    : `  - dotnet restore`

  return `before_script:
  - npm install -g appium
  - appium driver install ${driver}
  - appium &
  - sleep 5
${langScript}
`
}

function appiumTestScript(lang) {
  switch (lang) {
    case 'Java': return '    - mvn test'
    case 'Python': return '    - pytest -v'
    case 'JavaScript': return '    - npx wdio'
    case 'C#': return '    - dotnet test'
    default: return '    - mvn test'
  }
}

function generateGitlabReports(reports) {
  if (reports.junit) {
    return `\n  reports:\n    junit:\n      - test-results/**/*.xml`
  }
  return ''
}

export function generateCicdGitlabCiExplanation(model) {
  const p = model.pipeline
  return `## Pipeline Explanation: GitLab CI/CD

This GitLab CI/CD pipeline is configured to run ${p.automationFramework} tests using GitLab's integrated CI/CD system.

### Pipeline Structure

- **Stages**: The pipeline runs in ${p.automationFramework === 'playwright' ? 'a single' : 'two'} stage(s): ${p.automationFramework === 'playwright' ? 'test' : 'install and test'}.

- **Runner Image**: Uses ${p.automationFramework === 'playwright' ? 'the official Playwright Docker image (mcr.microsoft.com/playwright) which includes all browser dependencies' : 'the base OS image'}.

- **Dependencies**: ${p.automationFramework === 'playwright' ? 'Dependencies are installed via npm, and Playwright browsers are installed with system dependencies.' : p.automationFramework === 'selenium' ? `${p.language} dependencies are installed in the before_script stage.` : 'Appium is installed globally, the platform driver is configured, and the Appium server is started before tests.'}

### Key Features

- **Trigger**: Configured for ${p.trigger} events (via GitLab CI schedules for scheduled runs)
- **Image**: ${p.automationFramework === 'playwright' ? 'Playwright Docker image with pre-installed browsers' : 'Standard CI image'}
- **Artifacts**: Test results are retained for 7 days
- **Browser**: ${p.browser}

### Output Files

The pipeline generates a single \`.gitlab-ci.yml\` file that defines the entire CI/CD workflow.`
}

export function generateCicdGitlabCiChecklist(model) {
  const p = model.pipeline
  const items = []

  const checks = [
    { label: 'GitLab CI/CD platform selected', passed: true },
    { label: `${fwLabel(p.automationFramework)} framework selected`, passed: true },
    { label: `${p.language} language configured`, passed: true },
    { label: 'Dependencies installed correctly', passed: true },
    { label: `Pipeline triggers configured (${p.trigger})`, passed: true },
    { label: `${p.operatingSystem} operating system selected`, passed: true },
    { label: `${p.browser} browser configured`, passed: true },
    { label: `Headless mode recommended for CI`, passed: p.executionMode === 'Headless' },
    { label: 'JUnit report configuration', passed: p.reports.junit },
    { label: 'Artifacts configured for upload', passed: p.artifacts.reports || p.artifacts.screenshots || p.artifacts.videos || p.artifacts.logs },
  ]

  items.push({ category: 'Pipeline Validation', items: checks })

  const warnings = []
  if (!p.reports.junit) {
    warnings.push({ label: 'JUnit report not configured - test results may not be visible in GitLab UI', passed: false })
  }
  if (!p.artifacts.reports && !p.artifacts.screenshots && !p.artifacts.videos && !p.artifacts.logs) {
    warnings.push({ label: 'Missing artifact upload - test results will not be stored', passed: false })
  }
  if (p.executionMode === 'Headed') {
    warnings.push({ label: 'Headed mode not recommended for CI environments', passed: false })
  }
  if (warnings.length > 0) {
    items.push({ category: 'Warnings', items: warnings })
  }

  return items
}

export function generateCicdGitlabCiBestPractices() {
  return [
    {
      title: 'Use Specific Docker Images',
      description: 'Pin Docker images to specific tags (e.g., mcr.microsoft.com/playwright:v1.51.0-focal) for reproducible builds.',
    },
    {
      title: 'Configure Artifact Expiration',
      description: 'Set expire_in for artifacts to avoid filling up GitLab storage. 7 days is recommended for test results.',
    },
    {
      title: 'Leverage GitLab CI Cache',
      description: 'Use cache keyword to cache node_modules, .m2, or pip packages across pipeline runs for faster execution.',
    },
    {
      title: 'Use JUnit Reports for Visibility',
      description: 'Configure JUnit report uploads to see test results directly in the GitLab merge request UI.',
    },
    {
      title: 'Run Playwright in Headless Mode',
      description: 'Headless mode is essential in GitLab CI Docker runners where display servers are not available.',
    },
    {
      title: 'Separate Jobs for Different Browsers',
      description: 'Use parallel jobs or matrix builds to test across multiple browsers simultaneously.',
    },
    {
      title: 'Use GitLab Scheduled Pipelines',
      description: 'Schedule nightly test runs using GitLab CI schedules for regression testing.',
    },
  ]
}
