export function generateCicdAzureDevops(model) {
  const p = model.pipeline
  const fw = p.automationFramework
  const lang = p.language
  const os = p.operatingSystem.toLowerCase()
  const reports = p.reports
  const artifacts = p.artifacts
  const trigger = p.trigger

  const vmImage = os === 'macos' ? 'macOS-latest' : os === 'windows' ? 'windows-latest' : 'ubuntu-latest'

  const azureEnvLoad = buildAzureEnvLoad(p.projectVariables)
  const cacheStep = buildAzureCache(p.cacheConfig)
  const baseInstall = fw === 'playwright'
    ? `      - task: Npm@1
        displayName: 'Install Dependencies'
        inputs:
          command: 'install'
          workingDir: '$(System.DefaultWorkingDirectory)'

      - script: npx playwright install --with-deps
        displayName: 'Install Playwright Browsers'`
    : fw === 'selenium'
    ? seleniumAzureStep(lang)
    : appiumAzureStep(lang, p.platform)
  const installStep = azureEnvLoad + (cacheStep ? cacheStep + '\n' + baseInstall : baseInstall)

  const execMode = (p.executionOptions?.executionMode || p.executionMode || 'Headless').toLowerCase()
  const hasRetry = (p.executionOptions?.retries || 0) > 0 || p.enableRetry
  const workersFlag = (p.executionOptions?.workers || 0) > 1 ? ` --workers=${p.executionOptions.workers}` : ''
  const retriesFlag = (p.executionOptions?.retries || 0) > 0 ? ` --retries=${p.executionOptions.retries}` : ''
  const slowMoFlag = (p.executionOptions?.slowMo || 0) > 0 ? ` --slow-mo=${p.executionOptions.slowMo}` : ''
  const timeoutMinutes = p.executionOptions?.timeout || 60
  const suiteGrep = buildSuiteGrep(p.testSuites)
  const testStep = fw === 'playwright'
    ? `      - script: npx playwright test${execMode === 'headed' ? ' --headed' : ''}${reports.html ? '' : ' --reporter=list'}${suiteGrep}${workersFlag}${retriesFlag}${slowMoFlag}
        displayName: 'Run Tests'
        ${hasRetry ? 'continueOnError: true\n' : ''}timeoutInMinutes: ${timeoutMinutes}`
    : fw === 'selenium'
    ? seleniumAzureTestStep(lang)
    : appiumAzureTestStep(lang)

  const publishSteps = generateAzurePublishSteps(reports, artifacts)

  const triggerConfig = trigger === 'Scheduled Run'
    ? `schedules:
- cron: '0 6 * * 1-5'
  displayName: 'Weekday 6 AM Run'
  branches:
    include:
      - main`
    : trigger === 'Pull Request'
    ? `pr:
  branches:
    include:
      - main`
    : `trigger:
  branches:
    include:
      - main`

  const pipelineName = p.pipelineName || `${fwLabel(fw)} CI/CD Pipeline`

  let content = `# ${pipelineName}
# Generated by PlayGen CI/CD Generator
# Automation Framework: ${fwLabel(fw)} | Language: ${lang}
# https://playgen.app

${triggerConfig}

pool:
  vmImage: '${vmImage}'

variables:
  CI: true

steps:
${installStep}

${testStep}
${publishSteps}
`

  return [
    { name: 'azure-pipelines.yml', content: content.trimStart() },
  ]
}

function buildSuiteGrep(suites) {
  const enabled = (suites || []).filter((s) => s.enabled && s.tags && s.tags.length > 0)
  if (enabled.length === 0) return ''
  const tags = [...new Set(enabled.flatMap((s) => s.tags))]
  return ` --grep "${tags.join('|')}"`
}

function buildAzureCache(cacheConfig) {
  const pm = cacheConfig?.packageManager
  if (!pm) return ''
  const cacheConfigs = {
    npm: { key: 'npm', path: 'node_modules', file: 'package-lock.json' },
    maven: { key: 'maven', path: '.m2', file: 'pom.xml' },
    gradle: { key: 'gradle', path: '.gradle', file: '*.gradle*' },
    pip: { key: 'pip', path: '.cache/pip', file: 'requirements.txt' },
    nuget: { key: 'nuget', path: '.nuget/packages', file: '*.csproj' },
  }
  const cfg = cacheConfigs[pm]
  if (!cfg) return ''
  return `      - task: Cache@2
        displayName: 'Cache ${pm} Dependencies'
        inputs:
          key: ${cfg.key} | "$(Agent.OS)" | ${cfg.file}
          path: ${cfg.path}
          cacheHitVar: CACHE_RESTORED`
}

function buildAzureEnvLoad(vars) {
  const active = (vars || []).filter((v) => v.key)
  if (active.length === 0) return ''
  return `      - script: cat .env.variables | tee -a $(Build.SourcesDirectory)/.env
        displayName: 'Load Environment Variables'
        condition: succeeded()
`
}

function fwLabel(fw) {
  return { playwright: 'Playwright', selenium: 'Selenium', appium: 'Appium' }[fw] || fw
}

function seleniumAzureStep(lang) {
  switch (lang) {
    case 'Java':
      return `      - task: Maven@4
        displayName: 'Install Dependencies'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean install'
          options: '-DskipTests'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          jdkArchitectureOption: 'x64'`
    case 'Python':
      return `      - task: UsePythonVersion@0
        displayName: 'Setup Python'
        inputs:
          versionSpec: '3.11'

      - script: pip install -r requirements.txt
        displayName: 'Install Dependencies'`
    case 'JavaScript':
      return `      - task: Npm@1
        displayName: 'Install Dependencies'
        inputs:
          command: 'install'
          workingDir: '$(System.DefaultWorkingDirectory)'`
    case 'C#':
      return `      - task: DotNetCoreCLI@2
        displayName: 'Restore NuGet Packages'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'`
    default:
      return `      - task: Npm@1
        displayName: 'Install Dependencies'
        inputs:
          command: 'install'`
  }
}

function seleniumAzureTestStep(lang) {
  switch (lang) {
    case 'Java': return `      - task: Maven@4
        displayName: 'Run Tests'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'test'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'`
    case 'Python': return `      - script: pytest -v --junitxml=test-results/junit.xml
        displayName: 'Run Tests'
        continueOnError: true`
    case 'JavaScript': return `      - script: npx mocha --timeout 30000 --reporter mocha-junit-reporter
        displayName: 'Run Tests'
        continueOnError: true`
    case 'C#': return `      - task: DotNetCoreCLI@2
        displayName: 'Run Tests'
        inputs:
          command: 'test'
          projects: '**/*Tests.csproj'
          arguments: '--configuration Release'`
    default: return `      - script: mvn test
        displayName: 'Run Tests'`
  }
}

function appiumAzureStep(lang, platform) {
  const driver = platform === 'iOS' ? 'xcuitest' : 'uiautomator2'
  const langStep = lang === 'Java'
    ? `      - task: Maven@4
        displayName: 'Install Dependencies'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean install'
          options: '-DskipTests'`
    : lang === 'Python'
    ? `      - script: pip install -r requirements.txt
        displayName: 'Install Dependencies'`
    : lang === 'JavaScript'
    ? `      - task: Npm@1
        displayName: 'Install Dependencies'
        inputs:
          command: 'install'`
    : `      - task: DotNetCoreCLI@2
        displayName: 'Restore Packages'
        inputs:
          command: 'restore'`

  return `${langStep}

      - script: |
          npm install -g appium
          appium driver install ${driver}
        displayName: 'Setup Appium'

      - script: appium &
        displayName: 'Start Appium Server'`
}

function appiumAzureTestStep(lang) {
  switch (lang) {
    case 'Java': return `      - task: Maven@4
        displayName: 'Run Tests'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'test'
          publishJUnitResults: true`
    case 'Python': return `      - script: pytest -v
        displayName: 'Run Tests'
        continueOnError: true`
    case 'JavaScript': return `      - script: npx wdio
        displayName: 'Run Tests'
        continueOnError: true`
    case 'C#': return `      - task: DotNetCoreCLI@2
        displayName: 'Run Tests'
        inputs:
          command: 'test'
          projects: '**/*Tests.csproj'`
    default: return `      - script: mvn test
        displayName: 'Run Tests'`
  }
}

function generateAzurePublishSteps(reports, artifacts) {
  const steps = []

  if (reports.html) {
    steps.push(`      - script: mkdir -p reports && echo "Report" > reports/index.html
        displayName: 'Generate HTML Report'`)
  }

  if (reports.allure) {
    steps.push(`      - script: npm install -g allure-commandline && allure generate allure-results --clean -o allure-report
        displayName: 'Generate Allure Report'`)
  }

  if (reports.junit) {
    steps.push(`      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/test-results/**/*.xml'
          mergeTestResults: true
          failTaskOnFailedTests: false`)
  }

  const artifactPaths = []
  if (artifacts.reports) artifactPaths.push('reports')
  if (artifacts.screenshots) artifactPaths.push('screenshots')
  if (artifacts.videos) artifactPaths.push('videos')
  if (artifacts.logs) artifactPaths.push('logs')

  if (artifactPaths.length > 0) {
    steps.push(`      - task: PublishPipelineArtifact@1
        displayName: 'Publish Test Artifacts'
        condition: always()
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)'
          artifact: 'test-results'
          publishLocation: 'pipeline'`)
  }

  return steps.join('\n\n')
}

export function generateCicdAzureDevopsExplanation(model) {
  const p = model.pipeline
  return `## Pipeline Explanation: Azure DevOps

This Azure Pipeline is configured to run ${p.automationFramework} tests using Microsoft Azure DevOps Pipelines.

### Pipeline Structure

- **Trigger**: ${p.trigger === 'Scheduled Run' ? 'Scheduled to run weekdays at 6 AM' : `Configured to trigger on ${p.trigger.toLowerCase()} to the main branch`}

- **Build Agent**: Runs on a Microsoft-hosted ${p.operatingSystem} agent (vmImage: '${p.operatingSystem.toLowerCase() === 'macos' ? 'macOS-latest' : p.operatingSystem.toLowerCase() === 'windows' ? 'windows-latest' : 'ubuntu-latest'}')

- **Steps**:
  1. **Install Dependencies** - ${fwDepDesc(p)}
  2. **${fwStageLabel(p)}** - ${fwStageDesc(p)}
  3. **Run Tests** - Executes the test suite in ${p.executionMode.toLowerCase()} mode
  4. **Publish Results** - ${reportDesc(p.reports)}
  5. **Publish Artifacts** - ${artifactDesc(p.artifacts)}

### Key Features

- **Azure DevOps Integration**: Results appear in Azure Pipelines UI with test analytics
- **JUnit Publishing**: Test results are published in JUnit format for Azure integration
- **Artifact Publishing**: Pipeline artifacts are available for download from Azure DevOps

### Prerequisites

- Azure DevOps organization and project
- ${fwPrereq(p)}
- Appropriate build agent with ${p.automationFramework === 'playwright' ? 'Node.js' : p.language} installed`
}

function fwDepDesc(p) {
  if (p.automationFramework === 'playwright') return 'Installs npm dependencies via Npm task and Playwright browsers via script'
  if (p.automationFramework === 'selenium') return `Installs ${p.language} dependencies via ${p.language === 'Java' ? 'Maven task' : p.language === 'Python' ? 'pip script' : p.language === 'JavaScript' ? 'Npm task' : 'DotNetCoreCLI task'}`
  return 'Installs Appium globally, platform drivers, and project dependencies'
}

function fwStageLabel(p) {
  if (p.automationFramework === 'playwright') return 'Install Browsers'
  if (p.automationFramework === 'appium') return 'Setup Appium'
  return 'Setup'
}

function fwStageDesc(p) {
  if (p.automationFramework === 'playwright') return 'Installs Playwright browsers (Chromium, Firefox, WebKit) with system dependencies'
  if (p.automationFramework === 'appium') return `Installs Appium server and ${p.platform} driver`
  return ''
}

function reportDesc(reports) {
  const r = []
  if (reports.html) r.push('HTML report')
  if (reports.allure) r.push('Allure report')
  if (reports.junit) r.push('JUnit test results')
  return r.length > 0 ? `Publishes ${r.join(', ')}` : 'No reports configured'
}

function artifactDesc(artifacts) {
  const a = []
  if (artifacts.reports) a.push('test reports')
  if (artifacts.screenshots) a.push('screenshots')
  if (artifacts.videos) a.push('videos')
  if (artifacts.logs) a.push('logs')
  return a.length > 0 ? `Publishes ${a.join(', ')} as pipeline artifacts` : 'No artifacts configured'
}

function fwPrereq(p) {
  if (p.automationFramework === 'playwright') return 'Node.js installed on build agent (via UseNodeVersion task)'
  if (p.automationFramework === 'selenium') return `${p.language} runtime installed on build agent`
  return 'Node.js and Appium installed on build agent'
}

export function generateCicdAzureDevopsChecklist(model) {
  const p = model.pipeline
  const items = []

  const checks = [
    { label: 'Azure DevOps platform selected', passed: true },
    { label: `${fwLabel(p.automationFramework)} framework selected`, passed: true },
    { label: `${p.language} language configured`, passed: true },
    { label: 'Dependencies installed correctly', passed: true },
    { label: `Pipeline triggers configured (${p.trigger})`, passed: true },
    { label: `${p.operatingSystem} operating system selected`, passed: true },
    { label: `${p.browser} browser configured`, passed: true },
    { label: `Headless mode recommended for CI`, passed: p.executionMode === 'Headless' },
    { label: 'HTML report configuration', passed: p.reports.html },
    { label: 'Allure report configuration', passed: p.reports.allure },
    { label: 'JUnit XML report configuration', passed: p.reports.junit },
    { label: 'Artifacts configured for publish', passed: p.artifacts.reports || p.artifacts.screenshots || p.artifacts.videos || p.artifacts.logs },
  ]

  items.push({ category: 'Pipeline Validation', items: checks })

  const warnings = []
  if (!p.reports.html && !p.reports.allure && !p.reports.junit) {
    warnings.push({ label: 'Missing report configuration - no reports will be published', passed: false })
  }
  if (!p.artifacts.reports && !p.artifacts.screenshots && !p.artifacts.videos && !p.artifacts.logs) {
    warnings.push({ label: 'Missing artifact publish - test results will not be stored', passed: false })
  }
  if (p.executionMode === 'Headed') {
    warnings.push({ label: 'Headed mode not recommended for CI environments', passed: false })
  }
  if (warnings.length > 0) {
    items.push({ category: 'Warnings', items: warnings })
  }

  return items
}

export function generateCicdAzureDevopsBestPractices() {
  return [
    {
      title: 'Use Microsoft-Hosted Agents',
      description: 'Azure Pipelines offers Microsoft-hosted agents with pre-installed tools for Node.js, Java, Python, and .NET, reducing setup time.',
    },
    {
      title: 'Publish Test Results Natively',
      description: 'Use PublishTestResults@2 task to integrate test results directly into Azure DevOps test analytics and release gates.',
    },
    {
      title: 'Leverage Pipeline Artifacts',
      description: 'PublishPipelineArtifact@1 stores test reports and screenshots as Azure Pipeline artifacts for easy access from the pipeline run.',
    },
    {
      title: 'Use Multi-Platform Testing',
      description: 'Azure DevOps supports Ubuntu, Windows, and macOS agents. Use a strategy matrix to test across all platforms.',
    },
    {
      title: 'Configure Branch Policies',
      description: 'Set branch policies that require successful pipeline runs before merging pull requests to main branch.',
    },
    {
      title: 'Use Variable Groups',
      description: 'Store sensitive credentials (API keys, passwords) in Azure variable groups linked to Azure Key Vault for secure access.',
    },
    {
      title: 'Enable Continuous Validation',
      description: 'Configure CI triggers to run tests on every PR, and CD triggers to deploy after successful test runs on main branch.',
    },
  ]
}
