const D = '$'

export function generateCicdGithubActions(model) {
  const p = model.pipeline
  const fw = p.automationFramework
  const lang = p.language
  const os = p.operatingSystem.toLowerCase()
  const browser = p.browser.toLowerCase()
  const opts = p.executionOptions || {}
  const isParallel = opts.mode === 'parallel' || p.parallelExecution
  const hasRetry = (opts.retries || 0) > 0 || p.enableRetry
  const mode = (opts.executionMode || p.executionMode || 'Headless').toLowerCase()
  const reports = p.reports
  const artifacts = p.artifacts
  const trigger = p.trigger

  const triggers = {
    'Push': 'push:\n    branches: [ main, develop ]',
    'Pull Request': 'pull_request:\n    branches: [ main ]',
    'Manual Dispatch': 'workflow_dispatch:',
    'Scheduled Run': 'schedule:\n    - cron: \'0 6 * * 1-5\'',
  }

  const loadEnvStep = buildLoadEnvStep(p.projectVariables, 'github', p.activeEnvironment)
  const cacheStep = buildCacheStep(p.cacheConfig)
  const baseInstall = fw === 'playwright'
    ? `      - name: Install Dependencies\n        run: npm ci\n\n      - name: Install Playwright Browsers\n        run: npx playwright install --with-deps`
    : fw === 'selenium'
    ? seleniumInstall(lang)
    : appiumInstall(lang, p.platform)
  const installStep = cacheStep ? cacheStep + '\n' + baseInstall : baseInstall

  const workersFlag = opts.workers && opts.workers > 1 ? ` --workers=${opts.workers}` : ''
  const retriesFlag = opts.retries && opts.retries > 0 ? ` --retries=${opts.retries}` : ''
  const slowMoFlag = opts.slowMo && opts.slowMo > 0 ? ` --slow-mo=${opts.slowMo}` : ''
  const suiteGrep = buildSuiteGrep(p.testSuites)
  const testCmd = fw === 'playwright'
    ? `npx playwright test${mode === 'headed' ? ' --headed' : ''}${reports.html ? '' : ' --reporter=list'}${suiteGrep}${workersFlag}${retriesFlag}${slowMoFlag}`
    : fw === 'selenium'
    ? seleniumTestCmd(lang) + suiteGrep
    : appiumTestCmd(lang) + suiteGrep

  const timeoutMinutes = opts.timeout || 60
  const failFastEnabled = opts.failFast

  const reportUploadSteps = generateReportUploadSteps(reports)
  const artifactSteps = generateArtifactSteps(artifacts)

  const workflowName = p.pipelineName || `${fwLabel(fw)} CI/CD Pipeline`

  let content = `# ${workflowName}
# Generated by PlayGen CI/CD Generator
# Automation Framework: ${fwLabel(fw)} | Language: ${lang}
# https://playgen.app

name: ${workflowName}

on:
  ${triggers[trigger] || triggers['Push']}

env:
  CI: true${p.activeEnvironment ? `\n  APP_ENV: ${p.activeEnvironment}` : ''}

jobs:
  test:
    name: Run ${fwLabel(fw)} Tests
    runs-on: ${os === 'macos' ? 'macos-latest' : os === 'windows' ? 'windows-latest' : 'ubuntu-latest'}
${buildMatrixBlock(p.matrixConfig, isParallel, failFastEnabled)}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

${loadEnvStep}${installStep}

      - name: Run Tests
        run: ${testCmd}
${hasRetry ? `        continue-on-error: true` : ''}
        timeout-minutes: ${timeoutMinutes}

${reportUploadSteps}${artifactSteps}
`

  return [
    { name: '.github/workflows/pipeline.yml', content: content.trimStart() },
  ]
}

function buildSuiteGrep(suites) {
  const enabled = (suites || []).filter((s) => s.enabled && s.tags && s.tags.length > 0)
  if (enabled.length === 0) return ''
  const tags = [...new Set(enabled.flatMap((s) => s.tags))]
  return ` --grep "${tags.join('|')}"`
}

function buildCacheStep(cacheConfig) {
  const pm = cacheConfig?.packageManager
  if (!pm) return ''
  const cachePath = {
    npm: 'node_modules',
    maven: '~/.m2',
    gradle: '~/.gradle',
    pip: '~/.cache/pip',
    nuget: '~/.nuget/packages',
  }[pm]
  const hashFile = {
    npm: '**/package-lock.json',
    maven: '**/pom.xml',
    gradle: '**/*.gradle*',
    pip: '**/requirements.txt',
    nuget: '**/*.csproj',
  }[pm]
  if (!cachePath) return ''
  return `      - name: Cache ${pm} Dependencies
        uses: actions/cache@v4
        with:
          path: ${cachePath}
          key: ${D}{{ runner.os }}-${pm}-${D}{{ hashFiles('${hashFile}') }}
          restore-keys: |
            ${D}{{ runner.os }}-${pm}-
`
}

function buildLoadEnvStep(vars, platform, activeEnv) {
  const hasVars = (vars || []).some((v) => v.key)
  const hasEnv = !!activeEnv
  if (!hasVars && !hasEnv) return ''
  const lines = []
  if (platform === 'github') {
    if (hasVars) lines.push(`cat .env.variables >> ${D}GITHUB_ENV`)
    if (hasEnv) lines.push(`cat .env.${activeEnv} >> ${D}GITHUB_ENV`)
    if (lines.length === 0) return ''
    return `      - name: Load Environment Variables\n        run: |\n${lines.map((l) => `          ${l}`).join('\n')}\n\n`
  }
  return ''
}

function buildMatrixBlock(matrixConfig, isParallel, failFastEnabled) {
  const mc = matrixConfig || {}
  const browsers = mc.browsers || []
  const os = mc.os || []
  if (!isParallel || (browsers.length === 0 && os.length === 0)) return ''
  const parts = []
  if (browsers.length > 0) {
    parts.push(`        browser: [${browsers.map((b) => `'${b}'`).join(', ')}]`)
  }
  if (os.length > 0) {
    parts.push(`        os: [${os.map((o) => `'${o}'`).join(', ')}]`)
  }
  return `\n    strategy:\n      matrix:\n${parts.join('\n')}\n    fail-fast: ${failFastEnabled}\n`
}

function fwLabel(fw) {
  return { playwright: 'Playwright', selenium: 'Selenium', appium: 'Appium' }[fw] || fw
}

function seleniumInstall(lang) {
  switch (lang) {
    case 'Java':
      return `      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${D}{{ runner.os }}-maven-${D}{{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${D}{{ runner.os }}-maven-

      - name: Install Dependencies
        run: mvn clean install -DskipTests`
    case 'Python':
      return `      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt`
    case 'JavaScript':
      return `      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci`
    case 'C#':
      return `      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore NuGet Packages
        run: dotnet restore`
    default:
      return `      - name: Install Dependencies\n        run: npm ci`
  }
}

function seleniumTestCmd(lang) {
  switch (lang) {
    case 'Java': return 'mvn test'
    case 'Python': return 'pytest -v'
    case 'JavaScript': return 'npx mocha --timeout 30000'
    case 'C#': return 'dotnet test'
    default: return 'mvn test'
  }
}

function appiumInstall(lang, platform) {
  const base = platform === 'iOS' ? appiumIosInstall(lang) : appiumAndroidInstall(lang)
  return base
}

function appiumAndroidInstall(lang) {
  const langSetup = lang === 'Java'
    ? `      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${D}{{ runner.os }}-maven-${D}{{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${D}{{ runner.os }}-maven-

      - name: Install Dependencies
        run: mvn clean install -DskipTests`
    : lang === 'Python'
    ? `      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt`
    : lang === 'JavaScript'
    ? `      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci`
    : `      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore NuGet Packages
        run: dotnet restore`

  return `${langSetup}

      - name: Setup Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Start Appium Server
        run: |
          appium &
          sleep 5`
}

function appiumIosInstall(lang) {
  return appiumAndroidInstall(lang).replace('uiautomator2', 'xcuitest')
}

function appiumTestCmd(lang) {
  switch (lang) {
    case 'Java': return 'mvn test'
    case 'Python': return 'pytest -v'
    case 'JavaScript': return 'npx wdio'
    case 'C#': return 'dotnet test'
    default: return 'mvn test'
  }
}

function generateReportUploadSteps(reports) {
  const steps = []
  if (reports.html) {
    steps.push(`      - name: Generate HTML Report
        run: |
          mkdir -p reports
          echo "Report generated at $(date)" > reports/index.html`)
  }
  if (reports.allure) {
    steps.push(`      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.9
        with:
          allure_results: allure-results
          allure_history: allure-history`)
  }
  if (reports.junit) {
    steps.push(`      - name: Publish JUnit Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Tests
          path: '**/test-results/**/*.xml'
          reporter: java-junit`)
  }
  return steps.length > 0 ? steps.join('\n\n') + '\n\n' : ''
}

function generateArtifactSteps(artifacts) {
  const paths = []
  if (artifacts.reports) paths.push('reports/**')
  if (artifacts.screenshots) paths.push('**/screenshots/**')
  if (artifacts.videos) paths.push('**/videos/**')
  if (artifacts.logs) paths.push('**/logs/**')

  if (paths.length === 0) return ''

  return `      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            ${paths.join('\n            ')}
          retention-days: 7`
}

export function generateCicdGithubActionsExplanation(model) {
  const p = model.pipeline
  return `## Pipeline Explanation: GitHub Actions

This GitHub Actions workflow is configured to run ${p.automationFramework} tests automatically when ${p.trigger.toLowerCase()} events occur on your repository.

### Stages

1. **Checkout Source Code** - Uses actions/checkout@v4 to pull the latest code from the repository.

2. **Install Dependencies** - Sets up the appropriate runtime (Node.js, Java, Python, or .NET) and installs project dependencies ${depLabel(p)}.

3. **${p.automationFramework === 'playwright' ? 'Install Playwright Browsers' : p.automationFramework === 'appium' ? 'Setup Appium' : 'Install Drivers'}** - ${p.automationFramework === 'playwright' ? 'Installs the required Playwright browsers with system dependencies.' : p.automationFramework === 'appium' ? 'Installs Appium server and the required platform driver.' : 'Configures the WebDriver for browser automation.'}

4. **Run Tests** - Executes the test suite in ${p.executionMode.toLowerCase()} mode${p.parallelExecution ? ' with parallel execution across browsers' : ''}${p.enableRetry ? ' with retry on failure' : ''}.

5. **Generate Reports** - ${reportDesc(p.reports)}

6. **Upload Artifacts** - ${artifactDesc(p.artifacts)}

### Key Features

- **Trigger**: Configured for ${p.trigger} events
- **OS**: Runs on ${p.operatingSystem}
- **Browser**: ${p.browser}
- **Dependency Caching**: Maven/npm dependencies are cached for faster builds
- **Artifact Retention**: Test results are retained for 7 days`
}

function depLabel(p) {
  if (p.automationFramework === 'playwright') return '(npm ci)'
  if (p.automationFramework === 'selenium') {
    if (p.language === 'Java') return '(Maven)'
    if (p.language === 'Python') return '(pip)'
    if (p.language === 'JavaScript') return '(npm)'
    if (p.language === 'C#') return '(NuGet)'
  }
  return ''
}

function reportDesc(reports) {
  const r = []
  if (reports.html) r.push('HTML report')
  if (reports.allure) r.push('Allure report')
  if (reports.junit) r.push('JUnit XML report')
  return r.length > 0 ? `Generates ${r.join(', ')}` : 'No reports configured'
}

function artifactDesc(artifacts) {
  const a = []
  if (artifacts.reports) a.push('test reports')
  if (artifacts.screenshots) a.push('screenshots')
  if (artifacts.videos) a.push('videos')
  if (artifacts.logs) a.push('logs')
  return a.length > 0 ? `Archives ${a.join(', ')}` : 'No artifacts configured'
}

export function generateCicdGithubActionsChecklist(model) {
  const p = model.pipeline
  const items = []

  const checks = [
    { label: 'GitHub Actions platform selected', passed: true },
    { label: `${fwLabel(p.automationFramework)} framework selected`, passed: true },
    { label: `${p.language} language configured`, passed: true },
    { label: 'Dependencies installed correctly', passed: true },
    { label: `Pipeline triggers configured (${p.trigger})`, passed: true },
    { label: `${p.operatingSystem} operating system selected`, passed: true },
    { label: `${p.browser} browser configured`, passed: true },
    { label: `Headless mode recommended for CI`, passed: p.executionMode === 'Headless' },
    { label: 'HTML report configuration', passed: p.reports.html },
    { label: 'Allure report configuration', passed: p.reports.allure },
    { label: 'JUnit XML report configuration', passed: p.reports.junit },
    { label: 'Artifacts configured for upload', passed: p.artifacts.reports || p.artifacts.screenshots || p.artifacts.videos || p.artifacts.logs },
    { label: 'Dependency caching enabled', passed: true },
  ]

  items.push({ category: 'Pipeline Validation', items: checks })

  const warnings = []
  if (!p.reports.html && !p.reports.allure && !p.reports.junit) {
    warnings.push({ label: 'Missing report configuration - no reports will be generated', passed: false })
  }
  if (!p.artifacts.reports && !p.artifacts.screenshots && !p.artifacts.videos && !p.artifacts.logs) {
    warnings.push({ label: 'Missing artifact upload - test results will not be stored', passed: false })
  }
  if (p.executionMode === 'Headed') {
    warnings.push({ label: 'Headed mode not recommended for CI environments', passed: false })
  }
  if (warnings.length > 0) {
    items.push({ category: 'Warnings', items: warnings })
  }

  return items
}

export function generateCicdGithubActionsBestPractices() {
  return [
    {
      title: 'Use Specific Action Versions',
      description: 'Pin actions to specific SHAs or major versions (e.g., actions/checkout@v4) to ensure build stability and avoid unexpected breaking changes.',
    },
    {
      title: 'Leverage Dependency Caching',
      description: 'Cache Maven (~/.m2), npm (node_modules), or pip dependencies to reduce workflow execution time by 40-60% on subsequent runs.',
    },
    {
      title: 'Run Tests in Headless Mode',
      description: 'Always run browser tests in headless mode in CI to reduce resource usage and avoid display server dependencies.',
    },
    {
      title: 'Use Matrix Strategy for Cross-Browser Testing',
      description: 'Parallelize test execution across browsers using GitHub Actions matrix strategy to reduce total pipeline duration.',
    },
    {
      title: 'Upload Artifacts on Failure',
      description: 'Always use `if: always()` when uploading test artifacts to ensure screenshots and reports are available even when tests fail.',
    },
    {
      title: 'Set Appropriate Timeouts',
      description: 'Configure job-level and step-level timeouts to prevent runaway workflows from consuming CI minutes unnecessarily.',
    },
    {
      title: 'Separate Install and Test Stages',
      description: 'Keep dependency installation and test execution in separate steps for better cache utilization and clearer error reporting.',
    },
    {
      title: 'Use Service Containers for Dependencies',
      description: 'For integration tests, use GitHub Actions service containers to spin up databases or other required services.',
    },
  ]
}
