export const queryTemplates = [
  {
    id: 'verify-user-exists',
    category: 'Users',
    label: 'Verify User Exists',
    form: {
      databaseType: 'PostgreSQL',
      tableName: 'users',
      validationType: 'Record Exists',
      conditions: [{ column: 'email', operator: '=', value: 'user@example.com', logical: 'AND' }],
      joinEnabled: false,
      aggregateEnabled: false,
      orderColumn: '',
      orderDirection: 'DESC',
      limitEnabled: false,
      limitValue: '',
    },
  },
  {
    id: 'verify-user-deleted',
    category: 'Users',
    label: 'Verify User Deleted',
    form: {
      databaseType: 'PostgreSQL',
      tableName: 'users',
      validationType: 'Record Does Not Exist',
      conditions: [{ column: 'email', operator: '=', value: 'user@example.com', logical: 'AND' }],
      joinEnabled: false,
      aggregateEnabled: false,
      orderColumn: '',
      orderDirection: 'DESC',
      limitEnabled: false,
      limitValue: '',
    },
  },
  {
    id: 'verify-user-updated',
    category: 'Users',
    label: 'Verify User Updated',
    form: {
      databaseType: 'PostgreSQL',
      tableName: 'users',
      validationType: 'Verify Column Value',
      conditions: [{ column: 'id', operator: '=', value: '1', logical: 'AND' }],
      expectedColumn: 'status',
      expectedValue: 'active',
      joinEnabled: false,
      aggregateEnabled: false,
      orderColumn: '',
      orderDirection: 'DESC',
      limitEnabled: false,
      limitValue: '',
    },
  },
  {
    id: 'verify-order-created',
    category: 'Orders',
    label: 'Verify Order Created',
    form: {
      databaseType: 'PostgreSQL',
      tableName: 'orders',
      validationType: 'Record Exists',
      conditions: [{ column: 'order_id', operator: '=', value: '1001', logical: 'AND' }],
      joinEnabled: false,
      aggregateEnabled: false,
      orderColumn: '',
      orderDirection: 'DESC',
      limitEnabled: false,
      limitValue: '',
    },
  },
  {
    id: 'verify-payment-status',
    category: 'Orders',
    label: 'Verify Payment Status',
    form: {
      databaseType: 'PostgreSQL',
      tableName: 'payments',
      validationType: 'Verify Column Value',
      conditions: [{ column: 'order_id', operator: '=', value: '1001', logical: 'AND' }],
      expectedColumn: 'status',
      expectedValue: 'completed',
      joinEnabled: false,
      aggregateEnabled: false,
      orderColumn: '',
      orderDirection: 'DESC',
      limitEnabled: false,
      limitValue: '',
    },
  },
  {
    id: 'verify-product-exists',
    category: 'Inventory',
    label: 'Verify Product Exists',
    form: {
      databaseType: 'PostgreSQL',
      tableName: 'products',
      validationType: 'Record Exists',
      conditions: [{ column: 'sku', operator: '=', value: 'PROD-001', logical: 'AND' }],
      joinEnabled: false,
      aggregateEnabled: false,
      orderColumn: '',
      orderDirection: 'DESC',
      limitEnabled: false,
      limitValue: '',
    },
  },
  {
    id: 'verify-stock-updated',
    category: 'Inventory',
    label: 'Verify Stock Updated',
    form: {
      databaseType: 'PostgreSQL',
      tableName: 'inventory',
      validationType: 'Verify Column Value',
      conditions: [{ column: 'product_id', operator: '=', value: '1', logical: 'AND' }],
      expectedColumn: 'quantity',
      expectedValue: '50',
      joinEnabled: false,
      aggregateEnabled: false,
      orderColumn: '',
      orderDirection: 'DESC',
      limitEnabled: false,
      limitValue: '',
    },
  },
  {
    id: 'verify-audit-log',
    category: 'Audit',
    label: 'Verify Audit Log Created',
    form: {
      databaseType: 'PostgreSQL',
      tableName: 'audit_logs',
      validationType: 'Record Exists',
      conditions: [
        { column: 'action', operator: '=', value: 'USER_LOGIN', logical: 'AND' },
        { column: 'user_id', operator: '=', value: '1', logical: 'AND' },
      ],
      joinEnabled: false,
      aggregateEnabled: false,
      orderColumn: '',
      orderDirection: 'DESC',
      limitEnabled: false,
      limitValue: '',
    },
  },
  {
    id: 'verify-login-record',
    category: 'Authentication',
    label: 'Verify Login Record',
    form: {
      databaseType: 'PostgreSQL',
      tableName: 'sessions',
      validationType: 'Record Exists',
      conditions: [
        { column: 'user_id', operator: '=', value: '1', logical: 'AND' },
        { column: 'status', operator: '=', value: 'active', logical: 'AND' },
      ],
      joinEnabled: false,
      aggregateEnabled: false,
      orderColumn: '',
      orderDirection: 'DESC',
      limitEnabled: false,
      limitValue: '',
    },
  },
  {
    id: 'verify-session-record',
    category: 'Authentication',
    label: 'Verify Session Record',
    form: {
      databaseType: 'PostgreSQL',
      tableName: 'sessions',
      validationType: 'Latest Record',
      conditions: [{ column: 'user_id', operator: '=', value: '1', logical: 'AND' }],
      joinEnabled: false,
      aggregateEnabled: false,
      orderColumn: 'created_at',
      orderDirection: 'DESC',
      limitEnabled: true,
      limitValue: '1',
    },
  },
];

export const queryCategories = [
  'Users',
  'Orders',
  'Inventory',
  'Audit',
  'Authentication',
];
