export const seleniumTemplates = [
  {
    id: 'sel-login',
    name: 'Login',
    description: 'Verify user can log in with valid credentials',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'Authentication',
      module: 'Login',
      baseUrl: 'https://example.com',
      testTitle: 'Successful Login Test',
      author: '',
      priority: 'High',
      tags: ['Smoke', 'Critical'],
      description: 'Verify that a user can successfully log in with valid credentials.',
    },
    settings: { browser: 'Chrome', execution: 'Local', language: 'Java', framework: 'JUnit', reporting: 'Allure' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/login', description: 'Navigate to login page', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'username', value: '{{username}}', description: 'Enter username', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'password', value: '{{password}}', description: 'Enter password', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'login-button', value: '', description: 'Click login button', expectedValue: '', notes: '' },
      { action: 'Wait Until Visible', locatorType: 'CSS Selector', locator: '.welcome-message', value: '', description: 'Wait for dashboard', expectedValue: 'Dashboard should be visible', notes: '' },
    ],
    assertions: [
      { type: 'URL Contains', locatorType: 'CSS Selector', locator: '', value: '/dashboard' },
      { type: 'Element Visible', locatorType: 'CSS Selector', locator: '.welcome-message', value: '' },
    ],
    testData: [
      { name: 'username', value: 'standard_user' },
      { name: 'password', value: 'secret_sauce' },
    ],
  },
  {
    id: 'sel-registration',
    name: 'Registration',
    description: 'Verify new user registration flow',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'Authentication',
      module: 'Registration',
      baseUrl: 'https://example.com',
      testTitle: 'New User Registration Test',
      author: '',
      priority: 'High',
      tags: ['Regression', 'Critical'],
      description: 'Verify that a new user can register successfully.',
    },
    settings: { browser: 'Chrome', execution: 'Local', language: 'Java', framework: 'TestNG', reporting: 'Extent Reports' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/register', description: 'Navigate to registration page', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'full-name', value: '{{fullName}}', description: 'Enter full name', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'email', value: '{{email}}', description: 'Enter email', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'password', value: '{{password}}', description: 'Enter password', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'confirm-password', value: '{{password}}', description: 'Confirm password', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'register-button', value: '', description: 'Click register button', expectedValue: '', notes: '' },
      { action: 'Wait Until Visible', locatorType: 'CSS Selector', locator: '.success-message', value: '', description: 'Verify success message', expectedValue: 'Registration successful', notes: '' },
    ],
    assertions: [
      { type: 'Text Contains', locatorType: 'CSS Selector', locator: '.success-message', value: 'Registration successful' },
    ],
    testData: [
      { name: 'fullName', value: 'John Doe' },
      { name: 'email', value: 'john@example.com' },
      { name: 'password', value: 'SecurePass123!' },
    ],
  },
  {
    id: 'sel-logout',
    name: 'Logout',
    description: 'Verify user can log out successfully',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'Authentication',
      module: 'Logout',
      baseUrl: 'https://example.com',
      testTitle: 'User Logout Test',
      author: '',
      priority: 'Medium',
      tags: ['Smoke'],
      description: 'Verify that a logged-in user can log out successfully.',
    },
    settings: { browser: 'Firefox', execution: 'Local', language: 'Python', framework: 'Pytest', reporting: 'Built-in' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/dashboard', description: 'Navigate to dashboard', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'CSS Selector', locator: '.user-menu', value: '', description: 'Open user menu', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'Link Text', locator: 'Logout', value: '', description: 'Click logout', expectedValue: '', notes: '' },
      { action: 'Wait Until Visible', locatorType: 'ID', locator: 'login-button', value: '', description: 'Verify redirect to login', expectedValue: 'Should be on login page', notes: '' },
    ],
    assertions: [
      { type: 'URL Contains', locatorType: 'CSS Selector', locator: '', value: '/login' },
      { type: 'Element Visible', locatorType: 'ID', locator: 'login-button', value: '' },
    ],
    testData: [],
  },
  {
    id: 'sel-search',
    name: 'Search',
    description: 'Verify search functionality',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'Search',
      module: 'Search',
      baseUrl: 'https://example.com',
      testTitle: 'Product Search Test',
      author: '',
      priority: 'Medium',
      tags: ['Smoke', 'Regression'],
      description: 'Verify that search returns results for a valid query.',
    },
    settings: { browser: 'Chrome', execution: 'Headless', language: 'JavaScript', framework: 'Mocha', reporting: 'Allure' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/', description: 'Navigate to homepage', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'search-input', value: '{{searchQuery}}', description: 'Enter search query', expectedValue: '', notes: '' },
      { action: 'Press Key', locatorType: 'ID', locator: 'search-input', value: 'ENTER', description: 'Press enter to search', expectedValue: '', notes: '' },
      { action: 'Wait Until Visible', locatorType: 'CSS Selector', locator: '.search-results', value: '', description: 'Wait for results', expectedValue: 'Results should appear', notes: '' },
    ],
    assertions: [
      { type: 'Element Visible', locatorType: 'CSS Selector', locator: '.search-results', value: '' },
      { type: 'Text Contains', locatorType: 'CSS Selector', locator: '.result-count', value: 'results' },
    ],
    testData: [
      { name: 'searchQuery', value: 'laptop' },
    ],
  },
  {
    id: 'sel-checkout',
    name: 'Checkout',
    description: 'Verify complete checkout flow',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'Cart',
      module: 'Checkout',
      baseUrl: 'https://example.com',
      testTitle: 'Complete Checkout Test',
      author: '',
      priority: 'Critical',
      tags: ['Regression', 'Critical'],
      description: 'Verify the complete checkout flow from cart to order confirmation.',
    },
    settings: { browser: 'Edge', execution: 'Local', language: 'C#', framework: 'NUnit', reporting: 'Extent Reports' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/cart', description: 'Navigate to cart', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'checkout-button', value: '', description: 'Click checkout', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'first-name', value: '{{firstName}}', description: 'Enter first name', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'last-name', value: '{{lastName}}', description: 'Enter last name', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'zip-code', value: '{{zipCode}}', description: 'Enter zip code', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'continue-button', value: '', description: 'Continue to overview', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'finish-button', value: '', description: 'Finish checkout', expectedValue: '', notes: '' },
      { action: 'Wait Until Visible', locatorType: 'CSS Selector', locator: '.order-confirmation', value: '', description: 'Confirm order', expectedValue: 'Order confirmation should appear', notes: '' },
    ],
    assertions: [
      { type: 'Element Visible', locatorType: 'CSS Selector', locator: '.order-confirmation', value: '' },
      { type: 'Text Contains', locatorType: 'CSS Selector', locator: '.order-confirmation h1', value: 'Thank you' },
    ],
    testData: [
      { name: 'firstName', value: 'John' },
      { name: 'lastName', value: 'Doe' },
      { name: 'zipCode', value: '12345' },
    ],
  },
  {
    id: 'sel-shopping-cart',
    name: 'Shopping Cart',
    description: 'Verify add to cart functionality',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'Cart',
      module: 'Cart',
      baseUrl: 'https://example.com',
      testTitle: 'Add Items to Cart Test',
      author: '',
      priority: 'Medium',
      tags: ['Smoke', 'Regression'],
      description: 'Verify that items can be added to the cart.',
    },
    settings: { browser: 'Chrome', execution: 'Local', language: 'Java', framework: 'JUnit', reporting: 'Built-in' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/products', description: 'Navigate to products', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'CSS Selector', locator: '.add-to-cart', value: '', description: 'Add first item', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'CSS Selector', locator: '.add-to-cart', value: '', description: 'Add second item', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'CSS Selector', locator: '.cart-icon', value: '', description: 'Open cart', expectedValue: '', notes: '' },
    ],
    assertions: [
      { type: 'Text Contains', locatorType: 'CSS Selector', locator: '.cart-count', value: '2' },
      { type: 'Element Visible', locatorType: 'CSS Selector', locator: '.cart-item', value: '' },
    ],
    testData: [],
  },
  {
    id: 'sel-profile-update',
    name: 'Profile Update',
    description: 'Verify user profile update',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'User Profile',
      module: 'Profile',
      baseUrl: 'https://example.com',
      testTitle: 'Update User Profile Test',
      author: '',
      priority: 'Medium',
      tags: ['Regression'],
      description: 'Verify that a user can update their profile information.',
    },
    settings: { browser: 'Chrome', execution: 'Local', language: 'Python', framework: 'Pytest', reporting: 'Allure' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/profile', description: 'Navigate to profile', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'display-name', value: '{{displayName}}', description: 'Update display name', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'bio', value: '{{bio}}', description: 'Update bio', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'save-profile', value: '', description: 'Save profile', expectedValue: '', notes: '' },
      { action: 'Wait Until Visible', locatorType: 'CSS Selector', locator: '.success-toast', value: '', description: 'Verify success', expectedValue: 'Profile updated message', notes: '' },
    ],
    assertions: [
      { type: 'Text Contains', locatorType: 'CSS Selector', locator: '.success-toast', value: 'Profile updated' },
    ],
    testData: [
      { name: 'displayName', value: 'John Updated' },
      { name: 'bio', value: 'QA Engineer' },
    ],
  },
  {
    id: 'sel-forgot-password',
    name: 'Forgot Password',
    description: 'Verify password reset flow',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'Authentication',
      module: 'Password Reset',
      baseUrl: 'https://example.com',
      testTitle: 'Forgot Password Flow Test',
      author: '',
      priority: 'Medium',
      tags: ['Regression'],
      description: 'Verify that the forgot password flow works correctly.',
    },
    settings: { browser: 'Firefox', execution: 'Local', language: 'Java', framework: 'TestNG', reporting: 'Built-in' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/login', description: 'Navigate to login', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'Link Text', locator: 'Forgot Password?', value: '', description: 'Click forgot password link', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'email', value: '{{email}}', description: 'Enter email', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'reset-button', value: '', description: 'Click reset button', expectedValue: '', notes: '' },
      { action: 'Wait Until Visible', locatorType: 'CSS Selector', locator: '.reset-message', value: '', description: 'Verify confirmation', expectedValue: 'Reset link sent', notes: '' },
    ],
    assertions: [
      { type: 'Text Contains', locatorType: 'CSS Selector', locator: '.reset-message', value: 'Reset link sent' },
    ],
    testData: [
      { name: 'email', value: 'john@example.com' },
    ],
  },
  {
    id: 'sel-payment',
    name: 'Payment',
    description: 'Verify payment processing',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'Payments',
      module: 'Payment',
      baseUrl: 'https://example.com',
      testTitle: 'Process Payment Test',
      author: '',
      priority: 'Critical',
      tags: ['Smoke', 'Regression', 'Critical'],
      description: 'Verify that payment can be processed successfully.',
    },
    settings: { browser: 'Chrome', execution: 'Headless', language: 'JavaScript', framework: 'Mocha', reporting: 'Extent Reports' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/checkout', description: 'Navigate to checkout', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'card-number', value: '{{cardNumber}}', description: 'Enter card number', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'expiry', value: '{{expiryDate}}', description: 'Enter expiry', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'cvc', value: '{{cvc}}', description: 'Enter CVC', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'pay-button', value: '', description: 'Click pay', expectedValue: '', notes: '' },
      { action: 'Wait Until Visible', locatorType: 'CSS Selector', locator: '.payment-success', value: '', description: 'Verify payment success', expectedValue: 'Payment confirmation visible', notes: '' },
    ],
    assertions: [
      { type: 'Element Visible', locatorType: 'CSS Selector', locator: '.payment-success', value: '' },
      { type: 'Text Contains', locatorType: 'CSS Selector', locator: '.payment-success h1', value: 'Payment successful' },
    ],
    testData: [
      { name: 'cardNumber', value: '4111111111111111' },
      { name: 'expiryDate', value: '12/28' },
      { name: 'cvc', value: '123' },
    ],
  },
  {
    id: 'sel-crud',
    name: 'CRUD Operations',
    description: 'Verify create, read, update, delete',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'Data Management',
      module: 'CRUD',
      baseUrl: 'https://example.com',
      testTitle: 'CRUD Operations Test',
      author: '',
      priority: 'High',
      tags: ['Regression'],
      description: 'Verify the complete CRUD lifecycle for a resource.',
    },
    settings: { browser: 'Chrome', execution: 'Local', language: 'Java', framework: 'JUnit', reporting: 'Allure' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/items', description: 'Navigate to items list', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'add-new-button', value: '', description: 'Click add new', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'item-name', value: '{{itemName}}', description: 'Enter item name', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'save-button', value: '', description: 'Save item', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'CSS Selector', locator: '.edit-button', value: '', description: 'Edit item', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'ID', locator: 'item-name', value: '{{updatedName}}', description: 'Update item name', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'save-button', value: '', description: 'Save changes', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'CSS Selector', locator: '.delete-button', value: '', description: 'Delete item', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'CSS Selector', locator: '.confirm-delete', value: '', description: 'Confirm deletion', expectedValue: '', notes: '' },
    ],
    assertions: [
      { type: 'Element Visible', locatorType: 'CSS Selector', locator: '.items-list', value: '' },
    ],
    testData: [
      { name: 'itemName', value: 'Test Item' },
      { name: 'updatedName', value: 'Updated Item' },
    ],
  },
  {
    id: 'sel-alert-handling',
    name: 'Alert Handling',
    description: 'Verify JavaScript alert handling',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'UI',
      module: 'Alerts',
      baseUrl: 'https://example.com',
      testTitle: 'Alert Handling Test',
      author: '',
      priority: 'Medium',
      tags: ['Regression'],
      description: 'Verify that JavaScript alerts, confirms, and prompts are handled correctly.',
    },
    settings: { browser: 'Chrome', execution: 'Local', language: 'Python', framework: 'Pytest', reporting: 'Built-in' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/alerts', description: 'Navigate to alerts page', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'alert-button', value: '', description: 'Trigger alert', expectedValue: 'Alert appears', notes: '' },
      { action: 'Get Alert Text', locatorType: 'CSS Selector', locator: '', value: '', description: 'Read alert text', expectedValue: '', notes: '' },
      { action: 'Accept Alert', locatorType: 'CSS Selector', locator: '', value: '', description: 'Accept alert', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'confirm-button', value: '', description: 'Trigger confirm dialog', expectedValue: '', notes: '' },
      { action: 'Dismiss Alert', locatorType: 'CSS Selector', locator: '', value: '', description: 'Dismiss confirm', expectedValue: '', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'prompt-button', value: '', description: 'Trigger prompt dialog', expectedValue: '', notes: '' },
      { action: 'Send Alert Text', locatorType: 'CSS Selector', locator: '', value: 'Test input', description: 'Send text to prompt', expectedValue: '', notes: '' },
      { action: 'Accept Alert', locatorType: 'CSS Selector', locator: '', value: '', description: 'Accept prompt', expectedValue: '', notes: '' },
    ],
    assertions: [
      { type: 'Text Contains', locatorType: 'CSS Selector', locator: '.result', value: 'alert accepted' },
    ],
    testData: [],
  },
  {
    id: 'sel-window-handling',
    name: 'Window Handling',
    description: 'Verify browser window/tab management',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'UI',
      module: 'Windows',
      baseUrl: 'https://example.com',
      testTitle: 'Window Handling Test',
      author: '',
      priority: 'Medium',
      tags: ['Regression'],
      description: 'Verify that new windows and tabs are handled correctly.',
    },
    settings: { browser: 'Chrome', execution: 'Local', language: 'Java', framework: 'TestNG', reporting: 'Allure' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/', description: 'Navigate to homepage', expectedValue: '', notes: '' },
      { action: 'Open New Window', locatorType: 'CSS Selector', locator: '', value: '', description: 'Open new tab', expectedValue: 'New tab opens', notes: '' },
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/about', description: 'Navigate in new tab', expectedValue: '', notes: '' },
      { action: 'Switch Window', locatorType: 'CSS Selector', locator: '', value: '', description: 'Switch back to original tab', expectedValue: '', notes: '' },
      { action: 'Close Window', locatorType: 'CSS Selector', locator: '', value: '', description: 'Close current tab', expectedValue: '', notes: '' },
    ],
    assertions: [
      { type: 'URL Contains', locatorType: 'CSS Selector', locator: '', value: 'example.com' },
    ],
    testData: [],
  },
  {
    id: 'sel-iframe',
    name: 'Frame Handling',
    description: 'Verify iframe switching',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'UI',
      module: 'Frames',
      baseUrl: 'https://example.com',
      testTitle: 'iFrame Handling Test',
      author: '',
      priority: 'Medium',
      tags: ['Regression'],
      description: 'Verify that iframes are handled correctly.',
    },
    settings: { browser: 'Chrome', execution: 'Local', language: 'JavaScript', framework: 'Mocha', reporting: 'Built-in' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/frames', description: 'Navigate to frames page', expectedValue: '', notes: '' },
      { action: 'Switch To Frame', locatorType: 'CSS Selector', locator: '#content-frame', value: '', description: 'Switch to iframe', expectedValue: 'Inside iframe', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'frame-button', value: '', description: 'Click button in iframe', expectedValue: '', notes: '' },
      { action: 'Default Content', locatorType: 'CSS Selector', locator: '', value: '', description: 'Exit iframe', expectedValue: 'Back to main page', notes: '' },
    ],
    assertions: [
      { type: 'Element Visible', locatorType: 'CSS Selector', locator: '#content-frame', value: '' },
    ],
    testData: [],
  },
  {
    id: 'sel-dropdown',
    name: 'Dropdown Selection',
    description: 'Verify dropdown interactions',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'UI',
      module: 'Dropdown',
      baseUrl: 'https://example.com',
      testTitle: 'Dropdown Selection Test',
      author: '',
      priority: 'Low',
      tags: ['Regression'],
      description: 'Verify that dropdown selections work correctly.',
    },
    settings: { browser: 'Chrome', execution: 'Headless', language: 'Java', framework: 'JUnit', reporting: 'Allure' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/form', description: 'Navigate to form page', expectedValue: '', notes: '' },
      { action: 'Select By Text', locatorType: 'ID', locator: 'country', value: 'United States', description: 'Select country by visible text', expectedValue: '', notes: '' },
      { action: 'Select By Value', locatorType: 'ID', locator: 'language', value: 'en', description: 'Select language by value', expectedValue: '', notes: '' },
      { action: 'Select By Index', locatorType: 'ID', locator: 'currency', value: '0', description: 'Select currency by index', expectedValue: '', notes: '' },
    ],
    assertions: [
      { type: 'Text Equals', locatorType: 'CSS Selector', locator: '#selected-country', value: 'United States' },
    ],
    testData: [],
  },
  {
    id: 'sel-drag-drop',
    name: 'Drag and Drop',
    description: 'Verify drag and drop interaction',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'UI',
      module: 'Interactions',
      baseUrl: 'https://example.com',
      testTitle: 'Drag and Drop Test',
      author: '',
      priority: 'Low',
      tags: ['Regression'],
      description: 'Verify that drag and drop functionality works.',
    },
    settings: { browser: 'Chrome', execution: 'Local', language: 'Python', framework: 'Pytest', reporting: 'Extent Reports' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/drag-drop', description: 'Navigate to drag-drop page', expectedValue: '', notes: '' },
      { action: 'Drag And Drop', locatorType: 'ID', locator: 'draggable-1', value: '#dropzone', description: 'Drag item to drop zone', expectedValue: 'Item dropped successfully', notes: '' },
    ],
    assertions: [
      { type: 'Text Contains', locatorType: 'CSS Selector', locator: '#dropzone', value: 'dropped' },
    ],
    testData: [],
  },
  {
    id: 'sel-file-upload',
    name: 'File Upload',
    description: 'Verify file upload functionality',
    projectInfo: {
      projectName: 'My App',
      environment: 'Staging',
      feature: 'Upload',
      module: 'Files',
      baseUrl: 'https://example.com',
      testTitle: 'File Upload Test',
      author: '',
      priority: 'Medium',
      tags: ['Regression'],
      description: 'Verify that file upload works correctly.',
    },
    settings: { browser: 'Chrome', execution: 'Local', language: 'Java', framework: 'TestNG', reporting: 'Allure' },
    steps: [
      { action: 'Open URL', locatorType: 'CSS Selector', locator: '', value: 'https://example.com/upload', description: 'Navigate to upload page', expectedValue: '', notes: '' },
      { action: 'Type Text', locatorType: 'CSS Selector', locator: 'input[type="file"]', value: '/path/to/test-file.pdf', description: 'Select file to upload', expectedValue: 'File selected', notes: '' },
      { action: 'Click', locatorType: 'ID', locator: 'upload-button', value: '', description: 'Click upload button', expectedValue: '', notes: '' },
      { action: 'Wait Until Visible', locatorType: 'CSS Selector', locator: '.upload-success', value: '', description: 'Verify upload success', expectedValue: 'Upload successful message', notes: '' },
    ],
    assertions: [
      { type: 'Element Visible', locatorType: 'CSS Selector', locator: '.upload-success', value: '' },
    ],
    testData: [],
  },
]
