export const templates = [
  {
    id: 'login',
    name: 'Login',
    description: 'Verify user can log in with valid credentials',
    projectInfo: {
      projectName: 'My App',
      feature: 'Authentication',
      module: 'Login',
      baseUrl: 'https://example.com',
      testTitle: 'Successful Login',
      author: '',
      priority: 'High',
      tags: ['Smoke', 'Critical'],
      description: 'Verify that a user can successfully log in with valid credentials.',
    },
    steps: [
      { action: 'Open URL', locatorType: 'CSS', locator: '', value: '', description: 'Navigate to login page' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'username', value: '{{username}}', description: 'Enter username' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'password', value: '{{password}}', description: 'Enter password' },
      { action: 'Click', locatorType: 'Test ID', locator: 'login-button', value: '', description: 'Click login button' },
      { action: 'Wait For URL', locatorType: 'CSS', locator: '', value: '/dashboard', description: 'Wait for dashboard URL' },
    ],
    assertions: [
      { type: 'URL Contains', locatorType: 'CSS', locator: '', value: '/dashboard' },
      { type: 'Visible', locatorType: 'CSS', locator: '.welcome-message', value: '' },
    ],
    testData: [
      { name: 'username', value: 'standard_user' },
      { name: 'password', value: 'secret_sauce' },
    ],
  },
  {
    id: 'registration',
    name: 'Registration',
    description: 'Verify new user registration flow',
    projectInfo: {
      projectName: 'My App',
      feature: 'Authentication',
      module: 'Registration',
      baseUrl: 'https://example.com',
      testTitle: 'New User Registration',
      author: '',
      priority: 'High',
      tags: ['Regression', 'Critical'],
      description: 'Verify that a new user can register successfully.',
    },
    steps: [
      { action: 'Open URL', locatorType: 'CSS', locator: '', value: '/register', description: 'Navigate to registration page' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'full-name', value: '{{fullName}}', description: 'Enter full name' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'email', value: '{{email}}', description: 'Enter email' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'password', value: '{{password}}', description: 'Enter password' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'confirm-password', value: '{{password}}', description: 'Confirm password' },
      { action: 'Click', locatorType: 'Test ID', locator: 'register-button', value: '', description: 'Click register button' },
      { action: 'Verify Text', locatorType: 'CSS', locator: '.success-message', value: 'Registration successful', description: 'Verify success message' },
    ],
    assertions: [
      { type: 'Text Contains', locatorType: 'CSS', locator: '.success-message', value: 'Registration successful' },
    ],
    testData: [
      { name: 'fullName', value: 'John Doe' },
      { name: 'email', value: 'john@example.com' },
      { name: 'password', value: 'SecurePass123!' },
    ],
  },
  {
    id: 'logout',
    name: 'Logout',
    description: 'Verify user can log out successfully',
    projectInfo: {
      projectName: 'My App',
      feature: 'Authentication',
      module: 'Logout',
      baseUrl: 'https://example.com',
      testTitle: 'User Logout',
      author: '',
      priority: 'Medium',
      tags: ['Smoke'],
      description: 'Verify that a logged-in user can log out successfully.',
    },
    steps: [
      { action: 'Open URL', locatorType: 'CSS', locator: '', value: '/dashboard', description: 'Navigate to dashboard' },
      { action: 'Click', locatorType: 'Test ID', locator: 'user-menu', value: '', description: 'Open user menu' },
      { action: 'Click', locatorType: 'Text', locator: 'Logout', value: '', description: 'Click logout' },
      { action: 'Wait For URL', locatorType: 'CSS', locator: '', value: '/login', description: 'Redirect to login' },
    ],
    assertions: [
      { type: 'URL Contains', locatorType: 'CSS', locator: '', value: '/login' },
      { type: 'Visible', locatorType: 'Test ID', locator: 'login-button', value: '' },
    ],
    testData: [],
  },
  {
    id: 'forgot-password',
    name: 'Forgot Password',
    description: 'Verify password reset flow',
    projectInfo: {
      projectName: 'My App',
      feature: 'Authentication',
      module: 'Password Reset',
      baseUrl: 'https://example.com',
      testTitle: 'Forgot Password Flow',
      author: '',
      priority: 'Medium',
      tags: ['Regression'],
      description: 'Verify that the forgot password flow works correctly.',
    },
    steps: [
      { action: 'Open URL', locatorType: 'CSS', locator: '', value: '/login', description: 'Navigate to login' },
      { action: 'Click', locatorType: 'Text', locator: 'Forgot Password?', value: '', description: 'Click forgot password link' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'email', value: '{{email}}', description: 'Enter email' },
      { action: 'Click', locatorType: 'Test ID', locator: 'reset-button', value: '', description: 'Click reset button' },
      { action: 'Verify Text', locatorType: 'CSS', locator: '.reset-message', value: 'Reset link sent', description: 'Verify confirmation' },
    ],
    assertions: [
      { type: 'Text Contains', locatorType: 'CSS', locator: '.reset-message', value: 'Reset link sent' },
    ],
    testData: [
      { name: 'email', value: 'john@example.com' },
    ],
  },
  {
    id: 'search',
    name: 'Search',
    description: 'Verify search functionality',
    projectInfo: {
      projectName: 'My App',
      feature: 'Search',
      module: 'Search',
      baseUrl: 'https://example.com',
      testTitle: 'Product Search',
      author: '',
      priority: 'Medium',
      tags: ['Smoke', 'Regression'],
      description: 'Verify that search returns results for a valid query.',
    },
    steps: [
      { action: 'Open URL', locatorType: 'CSS', locator: '', value: '/', description: 'Navigate to homepage' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'search-input', value: '{{searchQuery}}', description: 'Enter search query' },
      { action: 'Press Enter', locatorType: 'Test ID', locator: 'search-input', value: '', description: 'Press enter to search' },
      { action: 'Wait For Visible', locatorType: 'CSS', locator: '.search-results', value: '', description: 'Wait for results' },
    ],
    assertions: [
      { type: 'Visible', locatorType: 'CSS', locator: '.search-results', value: '' },
      { type: 'Text Contains', locatorType: 'CSS', locator: '.result-count', value: 'results' },
    ],
    testData: [
      { name: 'searchQuery', value: 'laptop' },
    ],
  },
  {
    id: 'checkout',
    name: 'Checkout',
    description: 'Verify complete checkout flow',
    projectInfo: {
      projectName: 'My App',
      feature: 'Cart',
      module: 'Checkout',
      baseUrl: 'https://example.com',
      testTitle: 'Complete Checkout',
      author: '',
      priority: 'Critical',
      tags: ['Regression', 'Critical'],
      description: 'Verify the complete checkout flow from cart to order confirmation.',
    },
    steps: [
      { action: 'Open URL', locatorType: 'CSS', locator: '', value: '/cart', description: 'Navigate to cart' },
      { action: 'Click', locatorType: 'Test ID', locator: 'checkout-button', value: '', description: 'Click checkout' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'first-name', value: '{{firstName}}', description: 'Enter first name' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'last-name', value: '{{lastName}}', description: 'Enter last name' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'zip-code', value: '{{zipCode}}', description: 'Enter zip code' },
      { action: 'Click', locatorType: 'Test ID', locator: 'continue-button', value: '', description: 'Continue to overview' },
      { action: 'Click', locatorType: 'Test ID', locator: 'finish-button', value: '', description: 'Finish checkout' },
      { action: 'Wait For Visible', locatorType: 'CSS', locator: '.order-confirmation', value: '', description: 'Confirm order' },
    ],
    assertions: [
      { type: 'Visible', locatorType: 'CSS', locator: '.order-confirmation', value: '' },
      { type: 'Text Contains', locatorType: 'CSS', locator: '.order-confirmation h1', value: 'Thank you' },
    ],
    testData: [
      { name: 'firstName', value: 'John' },
      { name: 'lastName', value: 'Doe' },
      { name: 'zipCode', value: '12345' },
    ],
  },
  {
    id: 'shopping-cart',
    name: 'Shopping Cart',
    description: 'Verify add to cart and cart management',
    projectInfo: {
      projectName: 'My App',
      feature: 'Cart',
      module: 'Cart',
      baseUrl: 'https://example.com',
      testTitle: 'Add Items to Cart',
      author: '',
      priority: 'Medium',
      tags: ['Smoke', 'Regression'],
      description: 'Verify that items can be added to the cart and cart updates correctly.',
    },
    steps: [
      { action: 'Open URL', locatorType: 'CSS', locator: '', value: '/products', description: 'Navigate to products' },
      { action: 'Click', locatorType: 'Test ID', locator: 'add-to-cart-1', value: '', description: 'Add first item' },
      { action: 'Click', locatorType: 'Test ID', locator: 'add-to-cart-2', value: '', description: 'Add second item' },
      { action: 'Click', locatorType: 'Test ID', locator: 'cart-icon', value: '', description: 'Open cart' },
    ],
    assertions: [
      { type: 'Text Contains', locatorType: 'CSS', locator: '.cart-count', value: '2' },
      { type: 'Visible', locatorType: 'CSS', locator: '.cart-item', value: '' },
    ],
    testData: [],
  },
  {
    id: 'crud',
    name: 'CRUD Operations',
    description: 'Verify create, read, update, delete flow',
    projectInfo: {
      projectName: 'My App',
      feature: 'Data Management',
      module: 'CRUD',
      baseUrl: 'https://example.com',
      testTitle: 'CRUD Operations',
      author: '',
      priority: 'High',
      tags: ['Regression'],
      description: 'Verify the complete CRUD lifecycle for a resource.',
    },
    steps: [
      { action: 'Open URL', locatorType: 'CSS', locator: '', value: '/items', description: 'Navigate to items list' },
      { action: 'Click', locatorType: 'Test ID', locator: 'add-new-button', value: '', description: 'Click add new' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'item-name', value: '{{itemName}}', description: 'Enter item name' },
      { action: 'Click', locatorType: 'Test ID', locator: 'save-button', value: '', description: 'Save item' },
      { action: 'Click', locatorType: 'CSS', locator: '.edit-button:first', value: '', description: 'Edit item' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'item-name', value: '{{updatedName}}', description: 'Update item name' },
      { action: 'Click', locatorType: 'Test ID', locator: 'save-button', value: '', description: 'Save changes' },
      { action: 'Click', locatorType: 'CSS', locator: '.delete-button:first', value: '', description: 'Delete item' },
      { action: 'Click', locatorType: 'Text', locator: 'Confirm', value: '', description: 'Confirm deletion' },
    ],
    assertions: [
      { type: 'Visible', locatorType: 'CSS', locator: '.items-list', value: '' },
    ],
    testData: [
      { name: 'itemName', value: 'Test Item' },
      { name: 'updatedName', value: 'Updated Item' },
    ],
  },
  {
    id: 'profile-update',
    name: 'Profile Update',
    description: 'Verify user profile update',
    projectInfo: {
      projectName: 'My App',
      feature: 'User Profile',
      module: 'Profile',
      baseUrl: 'https://example.com',
      testTitle: 'Update User Profile',
      author: '',
      priority: 'Medium',
      tags: ['Regression'],
      description: 'Verify that a user can update their profile information.',
    },
    steps: [
      { action: 'Open URL', locatorType: 'CSS', locator: '', value: '/profile', description: 'Navigate to profile' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'display-name', value: '{{displayName}}', description: 'Update display name' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'bio', value: '{{bio}}', description: 'Update bio' },
      { action: 'Click', locatorType: 'Test ID', locator: 'save-profile', value: '', description: 'Save profile' },
      { action: 'Wait For Visible', locatorType: 'CSS', locator: '.success-toast', value: '', description: 'Verify success' },
    ],
    assertions: [
      { type: 'Text Contains', locatorType: 'CSS', locator: '.success-toast', value: 'Profile updated' },
    ],
    testData: [
      { name: 'displayName', value: 'John Updated' },
      { name: 'bio', value: 'QA Engineer' },
    ],
  },
  {
    id: 'payment',
    name: 'Payment',
    description: 'Verify payment processing',
    projectInfo: {
      projectName: 'My App',
      feature: 'Payments',
      module: 'Payment',
      baseUrl: 'https://example.com',
      testTitle: 'Process Payment',
      author: '',
      priority: 'Critical',
      tags: ['Smoke', 'Regression', 'Critical'],
      description: 'Verify that payment can be processed successfully.',
    },
    steps: [
      { action: 'Open URL', locatorType: 'CSS', locator: '', value: '/checkout', description: 'Navigate to checkout' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'card-number', value: '{{cardNumber}}', description: 'Enter card number' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'expiry', value: '{{expiryDate}}', description: 'Enter expiry' },
      { action: 'Fill', locatorType: 'Test ID', locator: 'cvc', value: '{{cvc}}', description: 'Enter CVC' },
      { action: 'Click', locatorType: 'Test ID', locator: 'pay-button', value: '', description: 'Click pay' },
      { action: 'Wait For Visible', locatorType: 'CSS', locator: '.payment-success', value: '', description: 'Verify payment success' },
    ],
    assertions: [
      { type: 'Visible', locatorType: 'CSS', locator: '.payment-success', value: '' },
      { type: 'Text Contains', locatorType: 'CSS', locator: '.payment-success h1', value: 'Payment successful' },
    ],
    testData: [
      { name: 'cardNumber', value: '4111111111111111' },
      { name: 'expiryDate', value: '12/28' },
      { name: 'cvc', value: '123' },
    ],
  },
];
